### ISSUE TITLE
SIGINT handler causes process to hang forever

### ISSUE THREAD

**Issue by zpnk** [wedgies/simple-express-json-logger#2]
The SIGINT event handler [here](https://github.com/wedgies/simple-express-json-logger/blob/master/index.js#L12-L19) causes a long-running node process (express, etc) to not exit when sent SIGINT.

To reproduce:
```js
// testy.js
var sejl = require('simple-express-json-logger');
var express = require('express');
var app = express();

app.listen(app.get('port'), function() {
  console.log("Express server listening on port " + app.get('port'));
});
```
`$ node testy.js`

Ctrl+C to exit the process and you will see "Got SIGINT.  Closing client." but the process won't actually exit. 

This issue also causes Node processes run under a task runner such as `nodemon` or `grunt` to become zombified on exit:

`$ nodemon testy.js`

Ctrl+C twice to exit, then run `$ ps aux | grep node` to see testy.js still running.

This is because once a SIGINT event handler is registered for a Node process it overrides the default and must explicitly call `process.exit()`. Obviously that is not desired for this functionality, so another approach is required. 

Something that may work would be to move the socket creation (`var client = dgram.createSocket('udp4');`) inside the `sendUDPMessage` method. Then, inside the `client.send` callback close out the client.

**Comment by slooker** [comment]
I removed the SIGINT handler and moved the client creation into the logger call.
